# Configuration for welcome - https://github.com/behaviorbot/welcome
newIssueWelcomeComment: >
  Thanks for opening your first issue here! Be sure to follow the new issue guideline!

newPRWelcomeComment: >
  Thanks for opening this pull request!

firstPRMergeComment: >
  Congrats on merging your first pull request! ğŸ¥³ğŸ‰
